import { useState } from 'react';
import { Upload, FileText, Loader2 } from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { categories } from '../utils/mockData';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from './ui/dialog';

export function UploadResolutionPage() {
  const [uploading, setUploading] = useState(false);
  const [uploadStep, setUploadStep] = useState(0);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [formData, setFormData] = useState({
    title: '',
    resolutionNumber: '',
    dateApproved: '',
    category: '',
  });

  const uploadSteps = [
    'Encrypting file...',
    'Uploading to IPFS...',
    'Recording to Blockchain...',
    'Complete!'
  ];

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setSelectedFile(e.target.files[0]);
    }
  };

  const handleUpload = async (e: React.FormEvent) => {
    e.preventDefault();
    setUploading(true);
    setUploadStep(0);

    // Simulate upload process
    for (let i = 0; i < uploadSteps.length; i++) {
      await new Promise(resolve => setTimeout(resolve, 1500));
      setUploadStep(i);
    }

    setTimeout(() => {
      setUploading(false);
      setUploadStep(0);
      setSelectedFile(null);
      setFormData({ title: '', resolutionNumber: '', dateApproved: '', category: '' });
    }, 2000);
  };

  // Mock auto-generated values
  const autoGenerated = {
    fileHash: 'a3f5d8e9c2b1a4f6e7d8c9b0a1f2e3d4c5b6a7f8e9d0c1b2a3f4e5d6c7b8a9f0',
    ipfsCID: 'QmX7Jk8fN9pL2mQ4rS6tV8wY0zB3cD5eF7gH9iJ1kL3mN5oP7',
    txId: '0x8f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3',
    timestamp: new Date().toISOString(),
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
      <div className="p-8">
        <div className="max-w-4xl mx-auto space-y-6">
          <div>
            <h1 className="text-3xl mb-2">Upload Document</h1>
            <p className="text-gray-600">Upload official barangay documents to the blockchain</p>
          </div>

          <form onSubmit={handleUpload}>
            <Card className="border-2 shadow-lg">
              <CardHeader className="bg-gradient-to-r from-blue-50 to-purple-50 border-b-2">
                <CardTitle>Document Information</CardTitle>
              </CardHeader>
              <CardContent className="space-y-6 pt-6">
                {/* Title */}
                <div className="space-y-2">
                  <Label htmlFor="title">Document Title</Label>
                  <Input
                    id="title"
                    value={formData.title}
                    onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                    placeholder="Enter document title"
                    className="border-2"
                    required
                  />
                </div>

                {/* Resolution Number */}
                <div className="space-y-2">
                  <Label htmlFor="resolutionNumber">Document Number</Label>
                  <Input
                    id="resolutionNumber"
                    value={formData.resolutionNumber}
                    onChange={(e) => setFormData({ ...formData, resolutionNumber: e.target.value })}
                    placeholder="e.g., BR-2025-001, BO-2025-001"
                    className="border-2"
                    required
                  />
                </div>

                {/* Date Approved */}
                <div className="space-y-2">
                  <Label htmlFor="dateApproved">Date Approved</Label>
                  <Input
                    id="dateApproved"
                    type="date"
                    value={formData.dateApproved}
                    onChange={(e) => setFormData({ ...formData, dateApproved: e.target.value })}
                    className="border-2"
                    required
                  />
                </div>

                {/* Category */}
                <div className="space-y-2">
                  <Label htmlFor="category">Category</Label>
                  <Select value={formData.category} onValueChange={(value) => setFormData({ ...formData, category: value })}>
                    <SelectTrigger id="category" className="border-2">
                      <SelectValue placeholder="Select category" />
                    </SelectTrigger>
                    <SelectContent>
                      {categories.map((category) => (
                        <SelectItem key={category} value={category}>
                          {category}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {/* File Upload */}
                <div className="space-y-2">
                  <Label htmlFor="file">Upload File (PDF/JPEG)</Label>
                  <div className="border-2 border-dashed rounded-xl p-8 text-center hover:border-blue-500 hover:bg-blue-50/50 transition-all cursor-pointer bg-gradient-to-br from-gray-50 to-blue-50/30">
                    <input
                      type="file"
                      id="file"
                      accept=".pdf,.jpg,.jpeg"
                      onChange={handleFileChange}
                      className="hidden"
                    />
                    <label htmlFor="file" className="cursor-pointer">
                      {selectedFile ? (
                        <div className="flex items-center justify-center gap-2">
                          <FileText className="w-8 h-8 text-blue-600" />
                          <div>
                            <p className="font-medium">{selectedFile.name}</p>
                            <p className="text-sm text-gray-600">{(selectedFile.size / 1024).toFixed(2)} KB</p>
                          </div>
                        </div>
                      ) : (
                        <div>
                          <Upload className="w-12 h-12 mx-auto text-gray-400 mb-2" />
                          <p className="text-gray-600">Click to upload or drag and drop</p>
                          <p className="text-sm text-gray-500 mt-1">PDF or JPEG (MAX. 10MB)</p>
                        </div>
                      )}
                    </label>
                  </div>
                </div>

                {/* Auto-Generated Fields */}
                <div className="border-t-2 pt-6 space-y-4">
                  <h3 className="font-semibold text-gray-700 flex items-center gap-2">
                    <FileText className="w-5 h-5 text-blue-600" />
                    Auto-Generated Blockchain Information
                  </h3>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label>SHA-256 File Hash</Label>
                      <Input value={autoGenerated.fileHash} disabled className="text-xs font-mono bg-gray-100 border-2" />
                    </div>

                    <div className="space-y-2">
                      <Label>IPFS CID</Label>
                      <Input value={autoGenerated.ipfsCID} disabled className="text-xs font-mono bg-gray-100 border-2" />
                    </div>

                    <div className="space-y-2">
                      <Label>Blockchain Transaction ID</Label>
                      <Input value={autoGenerated.txId} disabled className="text-xs font-mono bg-gray-100 border-2" />
                    </div>

                    <div className="space-y-2">
                      <Label>Timestamp</Label>
                      <Input value={new Date(autoGenerated.timestamp).toLocaleString()} disabled className="bg-gray-100 border-2" />
                    </div>
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="flex gap-4 pt-4">
                  <Button type="submit" className="flex-1 bg-blue-600 hover:bg-blue-700 h-12">
                    <Upload className="w-5 h-5 mr-2" />
                    Upload to Blockchain
                  </Button>
                  <Button type="button" variant="outline" className="flex-1 h-12 border-2">
                    Cancel
                  </Button>
                </div>
              </CardContent>
            </Card>
          </form>
        </div>
      </div>

      {/* Upload Progress Modal */}
      <Dialog open={uploading} onOpenChange={setUploading}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="text-2xl">Uploading Document</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            {uploadSteps.map((step, index) => (
              <div key={index} className="flex items-center gap-3">
                {index < uploadStep ? (
                  <div className="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center shadow-lg">
                    <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                  </div>
                ) : index === uploadStep ? (
                  <Loader2 className="w-8 h-8 text-blue-600 animate-spin" />
                ) : (
                  <div className="w-8 h-8 border-2 border-gray-300 rounded-full"></div>
                )}
                <span className={`text-lg ${index <= uploadStep ? 'text-gray-900' : 'text-gray-400'}`}>
                  {step}
                </span>
              </div>
            ))}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}